// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	Account     string
	AccountType string
	ImportRun   string
	Split       string
	TX          string
	TXImportRun string
}{
	Account:     "account",
	AccountType: "account_type",
	ImportRun:   "import_run",
	Split:       "split",
	TX:          "tx",
	TXImportRun: "tx_import_run",
}
