// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package query

import (
	"time"
)

type Tx struct {
	ID         int64     `json:"id"`
	DatePosted time.Time `json:"date_posted"`
	Memo       string    `json:"memo"`
}
