version: '3'

dotenv: ['{{.HOME}}/.txterm.env']

tasks:
  default:
    cmds:
      - go build -o ./txterm ./cmd/txterm
      - ./txterm import --file $TEST_OFX
  sqlc:generate:
    dir: internal/db
    cmds:
      - sqlc generate
