// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package query

import (
	"database/sql"
	"time"
)

type Account struct {
	ID            int64
	Name          string
	Description   sql.NullString
	AccountTypeID int64
}

type AccountType struct {
	ID   int64
	Name string
}

type Import struct {
	ID               int64
	DateCreated      time.Time
	Filename         string
	BalanceAmountNum sql.NullInt64
	BalanceAmountDen sql.NullInt64
	DateAsOf         sql.NullTime
}

type Tx struct {
	ID          int64
	DateCreated time.Time
	DatePosted  time.Time
	Memo        string
	AmountNum   int64
	AmountDen   int64
	ImportID    int64
}
